# Generated by Django 5.2.10 on 2026-01-25 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(help_text='Type of equipment to inspect (e.g., Server, Network Device)', max_length=100, verbose_name='Equipment Type')),
                ('cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=20, verbose_name='Inspection Cycle')),
                ('description', models.TextField(blank=True, help_text='Details about what should be inspected', verbose_name='Inspection Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_inspection_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_schedules', to='contracts.contract', verbose_name='Contract')),
            ],
            options={
                'verbose_name': 'Inspection Schedule',
                'verbose_name_plural': 'Inspection Schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(help_text='Date when inspection is scheduled', verbose_name='Scheduled Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_inspection_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='inspections.inspectionschedule', verbose_name='Schedule')),
            ],
            options={
                'verbose_name': 'Inspection Task',
                'verbose_name_plural': 'Inspection Tasks',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='InspectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal'), ('action_required', 'Action Required')], max_length=20, verbose_name='Result')),
                ('notes', models.TextField(blank=True, help_text='Detailed findings and observations', verbose_name='Notes')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Completed At')),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_results', to=settings.AUTH_USER_MODEL, verbose_name='Completed By')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='inspections.inspectiontask', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Inspection Result',
                'verbose_name_plural': 'Inspection Results',
                'ordering': ['-completed_at'],
            },
        ),
    ]
