# Generated by Django 6.0.1 on 2026-01-18 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('change', 'Change'), ('incident', 'Incident')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField()),
                ('detected_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('customer_notified', models.BooleanField(default=False)),
                ('customer_notified_at', models.DateTimeField(blank=True, null=True)),
                ('summary_notice', models.TextField(blank=True, help_text='1st notice summary')),
                ('audit_summary', models.TextField(blank=True, help_text='Audit/report summary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_incidents', to='contracts.contract')),
                ('related_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_events', to='events.changeincident')),
            ],
            options={
                'verbose_name_plural': 'Change/Incidents',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
