# Generated by Django 5.2.10 on 2026-02-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_add_evaluation_models'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='changeincident',
            index=models.Index(fields=['contract', 'record_type'], name='events_chan_contrac_1d7c89_idx'),
        ),
        migrations.AddIndex(
            model_name='changeincident',
            index=models.Index(fields=['occurred_at'], name='events_chan_occurre_c721b0_idx'),
        ),
    ]
