# Generated by Django 5.2.10 on 2026-02-14 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_changeincident_events_chan_contrac_1d7c89_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeincident',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='changeincident',
            name='original_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_incidents', to='events.changeincident'),
        ),
        migrations.AddField(
            model_name='changeincident',
            name='root_cause_category',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='changeincident',
            name='severity',
            field=models.IntegerField(blank=True, choices=[(1, '심각도 1'), (2, '심각도 2'), (3, '심각도 3')], null=True),
        ),
    ]
