# Generated by Django 6.0.1 on 2026-01-18 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('monthly', 'Monthly Report'), ('incident', 'Incident Report'), ('audit', 'Audit Report')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField(blank=True)),
                ('integrity_hash', models.CharField(blank=True, max_length=64)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='contracts.contract')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
