# Generated by Django 5.2.10 on 2026-02-14 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_a972ce_idx',
            old_name='notifications_recipient_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_4e3567_idx',
            old_name='notifications_recipient_is_read_idx',
        ),
    ]
