# Generated by Django 6.0.1 on 2026-01-18 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('client_org', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('scope_flags', models.CharField(blank=True, help_text='Comma-separated: ops,build,transition,pm', max_length=100)),
                ('status', models.CharField(choices=[('pre-handover', 'Pre-Handover'), ('handover', 'Handover'), ('stabilization', 'Stabilization'), ('steady', 'Steady State'), ('closed', 'Closed')], default='pre-handover', max_length=20)),
                ('risk_pre_env', models.BooleanField(default=False, verbose_name='Pre-existing Environment Risk')),
                ('risk_prior_vendor', models.BooleanField(default=False, verbose_name='Prior Vendor Coordination Required')),
                ('risk_docs_incomplete', models.BooleanField(default=False, verbose_name='Documentation Incomplete')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('pre-handover', 'Pre-Handover'), ('handover', 'Handover'), ('stabilization', 'Stabilization'), ('steady', 'Steady State'), ('closed', 'Closed')], max_length=20)),
                ('new_status', models.CharField(choices=[('pre-handover', 'Pre-Handover'), ('handover', 'Handover'), ('stabilization', 'Stabilization'), ('steady', 'Steady State'), ('closed', 'Closed')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='contracts.contract')),
            ],
            options={
                'verbose_name_plural': 'Contract status histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
