# Generated by Django 5.2.10 on 2026-02-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_add_evaluation_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='monthly_contract_amount',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='월간 계약금액 (벌점 계산 기준)', max_digits=15, null=True),
        ),
    ]
