# Generated by Django 6.0.1 on 2026-01-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(choices=[('pm', 'Project Manager'), ('engineer', 'Engineer'), ('joint', 'Joint Decision')], max_length=20)),
                ('rationale_checklist', models.JSONField(blank=True, default=dict, help_text='Structured flags for rationale categories')),
                ('rationale_notes', models.TextField(blank=True)),
                ('alternatives_considered', models.BooleanField(default=False)),
                ('risk_acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
