# Generated by Django 5.2.10 on 2026-06-11 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0002_initial'),
        ('tasks', '0006_add_related_incident_to_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionlog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decision_logs', to='tasks.task'),
        ),
    ]
