# Generated by Django 5.2.10 on 2026-02-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_add_evaluation_models'),
        ('tasks', '0003_fix_approval_required_data'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['contract', 'task_type'], name='tasks_task_contrac_b6a9ed_idx'),
        ),
    ]
