# Generated by Django 5.2.10 on 2026-02-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_tasks_task_contrac_b6a9ed_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='request_category',
            field=models.CharField(blank=True, choices=[('simple', '단순'), ('change', '변경'), ('replacement', '교체')], max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='target_completion_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
