# Generated by Django 5.2.10 on 2026-02-14 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_changeincident_is_duplicate_and_more'),
        ('tasks', '0005_task_request_category_task_target_completion_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='related_incident',
            field=models.ForeignKey(blank=True, help_text='연관 장애/변경 이벤트', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='events.changeincident'),
        ),
    ]
