# Generated by Django 6.0.1 on 2026-01-23 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttransaction',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmenttransaction',
            name='approver_role',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='equipmenttransaction',
            name='contract_status_at_approval',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='equipmenttransaction',
            name='operational_context_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmenttransaction',
            name='operational_context_type',
            field=models.CharField(blank=True, choices=[('incident', 'Incident'), ('change', 'Change Request'), ('task', 'Task')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='equipmenttransaction',
            name='pm_approval_obtained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipmenttransaction',
            name='requires_pm_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipmenttransaction',
            name='expected_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipmenttransaction',
            name='handler_affiliation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='equipmenttransaction',
            name='handler_contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipmenttransaction',
            name='handler_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipmenttransaction',
            name='purpose',
            field=models.TextField(verbose_name='Rationale'),
        ),
    ]
