# Generated by Django 6.0.1 on 2026-01-24 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_approval_fields_task004'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction_type', models.CharField(choices=[('equipment_data', 'Equipment Data Correction'), ('transaction_void', 'Transaction Void/Reversal'), ('status_override', 'Status Override'), ('other', 'Other Correction')], max_length=30)),
                ('description', models.TextField(help_text='Detailed explanation of the error and correction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('new_status', models.CharField(blank=True, choices=[('available', 'Available'), ('checked_out', 'Checked Out'), ('maintenance', 'Under Maintenance'), ('retired', 'Retired')], help_text='New status if this is a status override correction', max_length=20)),
                ('corrected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_corrections', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='equipments.equipment')),
                ('original_transaction', models.ForeignKey(blank=True, help_text='The transaction being corrected (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='equipments.equipmenttransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
