# Generated by Django 5.2.10 on 2026-01-25 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_equipmentcorrection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IPv4 or IPv6 address', null=True, verbose_name='IP Address'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='mac_address',
            field=models.CharField(blank=True, help_text='Media Access Control address (e.g., 00:1A:2B:3C:4D:5E)', max_length=17, null=True, verbose_name='MAC Address'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='operating_system',
            field=models.CharField(blank=True, help_text='OS name and version (e.g., Windows Server 2022, Ubuntu 22.04)', max_length=255, null=True, verbose_name='Operating System'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='purchase_date',
            field=models.DateField(blank=True, help_text='Date when equipment was purchased', null=True, verbose_name='Purchase Date'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, help_text='Date when warranty expires', null=True, verbose_name='Warranty Expiry Date'),
        ),
        migrations.CreateModel(
            name='AssetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Name of the field that changed', max_length=100, verbose_name='Field Name')),
                ('old_value', models.TextField(blank=True, help_text='Previous value', null=True, verbose_name='Old Value')),
                ('new_value', models.TextField(blank=True, help_text='New value', null=True, verbose_name='New Value')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who made the change (null for system changes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_history_changes', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(help_text='Equipment that was changed', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='equipments.equipment')),
            ],
            options={
                'verbose_name_plural': 'Asset History',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['equipment', '-changed_at'], name='equipments__equipme_c01830_idx'), models.Index(fields=['field_name', '-changed_at'], name='equipments__field_n_9a9bfc_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssetRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('depends_on', 'Depends On'), ('connected_to', 'Connected To'), ('powers', 'Powers'), ('backed_up_by', 'Backed Up By'), ('clustered_with', 'Clustered With'), ('replicates_to', 'Replicates To'), ('managed_by', 'Managed By')], max_length=20, verbose_name='Relationship Type')),
                ('description', models.TextField(blank=True, help_text='Additional details about the relationship')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(help_text='Source equipment', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='equipments.equipment')),
                ('related_equipment', models.ForeignKey(help_text='Target equipment', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='equipments.equipment')),
            ],
            options={
                'verbose_name_plural': 'Asset Relationships',
                'ordering': ['-created_at'],
                'unique_together': {('equipment', 'related_equipment', 'relationship_type')},
            },
        ),
    ]
