# Generated by Django 5.2.10 on 2026-02-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_add_evaluation_models'),
        ('equipments', '0004_equipment_ip_address_equipment_mac_address_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['contract', 'status'], name='equipments__contrac_6a5869_idx'),
        ),
    ]
