# Generated by Django 5.2.10 on 2026-02-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0005_equipment_equipments__contrac_6a5869_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='importance_grade',
            field=models.CharField(blank=True, choices=[('A', 'A등급'), ('B', 'B등급'), ('C', 'C등급')], default='C', help_text='장비 중요도 등급 (A: 2시간, B: 4시간, C: 8시간 복구목표)', max_length=1),
        ),
    ]
