# Generated by Django 5.2.10 on 2026-01-25 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLADefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(help_text='Type of service (e.g., Incident Response, Change Management)', max_length=255)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], help_text='Priority level for this SLA', max_length=20)),
                ('target_response_time_minutes', models.PositiveIntegerField(help_text='Target response time in minutes')),
                ('target_resolution_time_minutes', models.PositiveIntegerField(help_text='Target resolution time in minutes')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_definitions', to='contracts.contract')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('contract', 'service_type', 'priority')},
            },
        ),
        migrations.CreateModel(
            name='SLAMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('actual_response_time_minutes', models.PositiveIntegerField(blank=True, help_text='Actual response time in minutes', null=True)),
                ('actual_resolution_time_minutes', models.PositiveIntegerField(blank=True, help_text='Actual resolution time in minutes', null=True)),
                ('response_sla_met', models.BooleanField(blank=True, help_text='Whether response time SLA was met', null=True)),
                ('resolution_sla_met', models.BooleanField(blank=True, help_text='Whether resolution time SLA was met', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('sla_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='sla.sladefinition')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
