# Generated by Django 5.2.10 on 2026-02-14 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_monthly_contract_amount'),
        ('equipments', '0006_equipment_importance_grade'),
        ('sla', '0002_add_evaluation_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaevaluationreport',
            name='adjustment_points',
            field=models.IntegerField(default=0, help_text='Bonus/penalty from duplicates and improvements'),
        ),
        migrations.AddField(
            model_name='slaevaluationreport',
            name='duplicate_incident_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='slaevaluationreport',
            name='improvement_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PerformanceImprovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('proposed_by', models.CharField(blank=True, max_length=100)),
                ('proposed_date', models.DateField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('accepted_date', models.DateField(blank=True, null=True)),
                ('effect_report', models.TextField(blank=True, help_text='실질개선 효과 결과 보고서')),
                ('evaluation_period_start', models.DateField(blank=True, null=True)),
                ('evaluation_period_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_improvements', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Performance Improvement',
                'verbose_name_plural': 'Performance Improvements',
                'ordering': ['-proposed_date'],
            },
        ),
        migrations.CreateModel(
            name='SLAPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_type', models.CharField(choices=[('overall', '종합평가 벌점'), ('item_level', '항목별 벌점')], max_length=20)),
                ('penalty_rate', models.DecimalField(decimal_places=2, help_text='Penalty percentage', max_digits=5)),
                ('penalty_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('is_offset', models.BooleanField(default=False, help_text='Whether this penalty is offset by annual adjustment')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sla.slaevaluationitem')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='sla.slaevaluationreport')),
            ],
            options={
                'verbose_name': 'SLA Penalty',
                'verbose_name_plural': 'SLA Penalties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SLARevisionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=100)),
                ('requester_department', models.CharField(max_length=100)),
                ('request_date', models.DateField()),
                ('revision_reason', models.TextField()),
                ('document_name', models.CharField(blank=True, max_length=200)),
                ('section_reference', models.CharField(blank=True, max_length=100)),
                ('content_before', models.TextField()),
                ('content_after', models.TextField()),
                ('review_opinion', models.TextField(blank=True)),
                ('review_result', models.CharField(blank=True, choices=[('approved', '개정'), ('needs_review', '추가검토'), ('rejected', '의견반려')], max_length=20)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('reviewer_name', models.CharField(blank=True, max_length=100)),
                ('reviewer_department', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_revision_requests', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'SLA Revision Request',
                'verbose_name_plural': 'SLA Revision Requests',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='SLAEvaluationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_level', models.DecimalField(decimal_places=1, help_text='Service level: 1.0, 0.8, 0.6, 0.4, 0.2', max_digits=3)),
                ('criteria_text', models.TextField(help_text='Description of criteria for this level')),
                ('evaluation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='sla.slaevaluationitem')),
            ],
            options={
                'verbose_name': 'SLA Evaluation Criteria',
                'verbose_name_plural': 'SLA Evaluation Criteria',
                'ordering': ['evaluation_item__item_number', '-service_level'],
                'unique_together': {('evaluation_item', 'service_level')},
            },
        ),
        migrations.CreateModel(
            name='UptimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_operating_hours', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unplanned_downtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('uptime_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('downtime_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uptime_records', to='contracts.contract')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uptime_records', to='equipments.equipment')),
            ],
            options={
                'verbose_name': 'Uptime Record',
                'verbose_name_plural': 'Uptime Records',
                'ordering': ['-period_start'],
                'unique_together': {('equipment', 'period_start', 'period_end')},
            },
        ),
    ]
